import { Hero } from './templates';

export const HEROES: Hero[] = [
    {
        id: 1,
        name: 'Abaddon',
        attributeType: 'Universal',
        theme: 'tertiary',
        tag: 'Support, Carry, Durable',
        shortDescription: "Shields his allies or himself from attacks.",
        description: "Unlike the other scions of his house, Abaddon drank deeper than any from the prophetic vapors that flowed from the Font of Avernus. Now a being of unnatural powers, Abaddon stifles his foes by spreading the Curse of Avernus, and releases deathly double-edged Mist Coils to damage adversaries and heal allies. The black mist swirls around his compatriots, forming an Aphotic Shield that absorbs attacks before bursting in a wide radius. But the Font's greatest gift is revealed only in the desperation of battle.Bestowed with Borrowed Time, Abaddon charges the enemy ranks, riding down foes with his cursed blade, his health returning with each welcoming blow.For all that was meant to kill did nothing but make the Lord of Avernus even more formidable.",
        realName: "Abaddon, the Lord of Avernus",
        history1: "The Font of Avernus is the source of a family's strength, a crack in primal stones from which vapors of prophetic power have issued for generations. Each newborn of the cavernous House Avernus is bathed in the black mist, and by this baptism they are given an innate connection to the mystic energies of the land. They grow up believing themselves fierce protectors of their lineal traditions, the customs of the realm—but what they really are protecting is the Font itself. And the motives of the mist are unclear.",
        history2: "When the infant Abaddon was bathed in the Font, they say something went awry. In the child's eyes there flared a light of comprehension that startled all present and set the sacerdotes to whispering. He was raised with every expectation of following the path all scions of Avernus took—to train in war, that in times of need he might lead the family's army in defense of the ancestral lands. But Abaddon was always one apart. Where others trained with weapons, he bent himself to meditation in the presence of the mist. He drank deep from the vapors that welled from the Font, learning to blend his spirit with the potency that flowed from far beneath the House; he became a creature of the black mist.",
        history3: "There was bitterness within the House Avernus—elders and young alike accusing him of neglecting his responsibilities. But all such accusations stopped when Abaddon rode into battle, and they saw how the powers of the mist had given him mastery over life and death beyond those of any lord the House had ever known.",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Abaddon_icon.webp',
        bodyPic: 'assets/images/heroes/abaddon.jpg',
        attributePic: 'assets/images/heroes/icons/universal.png',
        starred: false,
        winRates: [55.68, 55.57, 55.15, 54.63, 53.50],
        pickRates: [7.44, 8.91, 9.60, 9.99, 9.61],
    },
    {
        id: 2,
        name: 'Alchemist',
        attributeType: 'Strength',
        theme: 'danger',
        tag: 'Carry, Durable',
        shortDescription: "Earns extra gold from unit kills and bounty runes.",
        description: "Having broken out of prison with his ogre accomplice, Razzil Darkbrew embarks on the search for new materials to use in his transmutations. Learned in alchemy, he infuses his partner's weapons with Corrosive Substances and created toxic Sludge Acids to accelerate his Greevil's Greed — extracting extra gold from creeps and Bounty Rune minimap icon Bounty Runes. With enough resources, it is rumored that Razzil has the secret formula to Synthesize a buff into the body that equals the legendary scepter. The Alchemist brews, atop the shoulders of his companion, an increasingly Unstable Concoction that is ideally thrown before it explodes. In a pinch, Razzil slips his partner with an Unknown Potion, inducing a Chemical Rage in the ogre's body. Symptoms include unnatural speeds, rapid health regeneration, and a pleasant purple hue. ",
        realName: "Razzil Darkbrew, the Alchemist",
        history1: "The sacred science of Chymistry was a Darkbrew family tradition, but no Darkbrew had ever shown the kind of creativity, ambition, and recklessness of young Razzil. However, when adulthood came calling he pushed aside the family trade to try his hand at manufacturing gold through Alchemy.",
        history2: "In an act of audacity befitting his reputation, Razzil announced he would transmute an entire mountain into gold. Following two decades of research and spending and preparation, he failed spectacularly, quickly finding himself imprisoned for the widespread destruction his experiment wrought. Yet Razzil was never one to take a setback lightly, and sought escape to continue his research.",
        history3: "When his new cellmate turned out to be a fierce ogre, he found just the opportunity he needed. After convincing the ogre not to eat him, Razzil set about carefully concocting a tincture for it to drink, made from the moulds and mosses growing in the prison stone work. In a week's time, it seemed ready. When the ogre drank the potion, it flew into an unstoppable berserker rage, destroying the cell bars and exploding through walls and guards alike.",
        history4: "They soon found themselves lost somewhere in the forest surrounding the city with a trail of wreckage in their wake and no signs of pursuit. In the tonic's afterglow, the ogre seemed serene, happy, and even eager. Resolving to work together, the pair set off to collect the materials needed to attempt Razzil's Alchemic transmutation once more.",
        profilePic: 'assets/images/heroes/icons/Alchemist_icon.webp',
        bodyPic: 'assets/images/heroes/alchemist.jpg',
        attributePic: 'assets/images/heroes/icons/strength.png',
        starred: false,
        winRates: [46.88, 48.10, 48.91, 49.71, 48.32,],
        pickRates: [2.96, 2.81, 2.80, 2.85, 2.99],
    },
    {
        id: 3,
        name: 'Ancient Apparition',
        attributeType: 'Intelligent',
        theme: 'primary',
        tag: 'Support, Nuker',
        shortDescription: "Launches a powerful icy blast from anywhere on the map.",
        description: "Projected from the cold, infinite void, the Ancient Apparition known as Kaldr is but a faint image of his true self. Nevertheless, his Chilling Touch is enough to reach the furthest of targets. Caught in an Ice Vortex, heroes quickly get Cold Feet and before they know it, find themselves frozen in place. A frigid sphere flies across the sky, expanding at its destination. Within seconds, an Ice Blast strikes the marked area. Flash frozen, enemies have no choice but to retreat before their brittle bodies shatter to pieces.",
        realName: "Kaldr, the Ancient Apparition",
        history1: "Kaldr, the Ancient Apparition, is an image projected from outside time. He springs from the cold, infinite void that both predates the universe and awaits its end. Kaldr is, Kaldr was, Kaldr shall be… and what we perceive, powerful as it appears to us, is but the faintest faded echo of the true, eternal Kaldr. Some believe that as the cosmos ages and approaches its final moments, the brightness and power of Kaldr will also intensify—that the Ancient Apparition will grow younger and stronger as eternity's end draws nigh. His grip of ice will bring all matter to a stop, his image will cast a light too terrible to behold. An Apparition no longer!",
        history2: "",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Ancient_Apparition_icon.webp',
        bodyPic: 'assets/images/heroes/ancient_apparition.jpg',
        attributePic: 'assets/images/heroes/icons/intelligent.png',
        starred: false,
        winRates: [50.97, 51.20, 50.56, 50.12, 49.29],
        pickRates: [7.12, 7.45, 7.04, 6.29, 4.83],
    },
    {
        id: 4,
        name: 'Anti-Mage',
        attributeType: 'Agility',
        theme: 'success',
        tag: 'Carry, Escape',
        shortDescription: "Slashes his foes with mana-draining attacks.",
        description: "Among the ascetic monks of Turstarkuri, only a young acolyte was fortunate enough to escape the fallen legion's assault on the monastery. Now, vowing to eliminate not only the magic of the Dead God, the Anti-Mage returns to eradicate magic altogether. With sheer focus, he Counters Spells thrown at him and his Allies, returning them to their senders. No wizard's trick is enough to contain or elude the Anti-Mage, as he Blinks out of any trap, while at the same time being capable of sending a Fragments of himself to pursue targets in return. With each swing of his unorthodox blades, the Anti-Mage steps closer to his goal of erradicating all magic, Breaking apart Mana, setting up the depleted caster to perish in a crushing Mana Void.",
        realName: "Magina, the Anti-Mage",
        history1: "The monks of Turstarkuri watched the rugged valleys below their mountain monastery as wave after wave of invaders swept through the lower kingdoms. Ascetic and pragmatic, in their remote monastic eyrie they remained aloof from mundane strife, wrapped in meditation that knew no gods or elements of magic. Then came the Legion of the Dead God, crusaders with a sinister mandate to replace all local worship with their unliving lord's poisonous nihilosophy. From a landscape that had known nothing but blood and battle for a thousand years, they tore the souls and bones of countless fallen legions and pitched them against Turstarkuri. The monastery stood scarcely a fortnight against the assault, and the few monks who bothered to surface from their meditations believed the invaders were but demonic visions sent to distract them from meditation. They died where they sat on their silken cushions. Only one youth survived--a pilgrim who had come as an acolyte, seeking wisdom, but had yet to be admitted to the monastery. He watched in horror as the monks to whom he had served tea and nettles were first slaughtered, then raised to join the ranks of the Dead God's priesthood. With nothing but a few of Turstarkuri's prized dogmatic scrolls, he crept away to the comparative safety of other lands, swearing to obliterate not only the Dead God's magic users--but to put an end to magic altogether.",
        history2: "",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Anti-Mage_icon.webp',
        bodyPic: 'assets/images/heroes/antimage.jpg',
        attributePic: 'assets/images/heroes/icons/agility.png',
        starred: false,
        winRates: [52.07, 52.70, 52.53, 52.26, 51.08],
        pickRates: [17.31, 16.37, 15.6, 15.21, 14.35],
    },
    {
        id: 5,
        name: 'Arc Warden',
        attributeType: 'Agility',
        theme: 'success',
        tag: 'Carry, Escape',
        shortDescription: "Creates a copy of himself to split push.",
        description: "A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.",
        realName: "Zet, the Arc Warden",
        history1: "Before the beginning of all, there existed a presence: a primordial mind, infinite, awesome, and set to inscrutable purpose. As the universe thundered into being, this mind was fragmented and scattered. Two among its greater fragments—who would come to be named Radiant and Dire--found themselves locked in vicious opposition, and began twisting all of creation to serve their conflict.",
        history2: "As war and cataclysm threatened the nascent cosmos, the will of a third fragment made itself known. Naming itself Zet, this intellect sought to resolve the disharmony and return all to perfect unity. Appalled by its kin's conflicting nature, Zet gathered the sum of its power. In a sudden flash, it overwhelmed its siblings, and fused the warring aspects into a stellar sphere before hurling them into the darkness to orbit a nondescript world. Harmony was restored, though only the barest fraction of Zet's strength remained. Setting its gaze on the prison, Zet chose to use its weakened power to serve as watchful warden until time's end. For uncounted aeons, this vigil stood.",
        history3: "Life flourished upon the world below, oblivious to the dangers imprisoned within the softly glowing moon, or of Zet's struggles to contain them. As the captives' eternal clash reverberated within, the surface of the prison shuddered, over time beginning to crack. Ultimately, Zet's depleted power proved insufficient to contain the breach, and at last the moon was shattered. The prison's ancient inhabitants had escaped to sow their conflict anew.",
        history4: "Flung to the farthest reaches by the prison's explosion, Zet was transformed by the dissonant energies of its former captives. No longer of single form and thought, its presence had become split among many—some lesser, some greater—each connected by a fleeting arc of consciousness. Struggling to suppress its own disunity, Zet sped toward the burgeoning conflict of its siblings, bending its fractured wills toward a singular conclusion: the aspects of the primordial mind must be made to reunite, or all must be destroyed lest the conflict spread further…",
        profilePic: 'assets/images/heroes/icons/Arc_Warden_icon.webp',
        bodyPic: 'assets/images/heroes/arc_warden.jpg',
        attributePic: 'assets/images/heroes/icons/agility.png',
        starred: false,
        winRates: [53.43, 54.08, 54.16, 54.33, 53.42],
        pickRates: [8.15, 5.51, 4.61, 4.39, 4.02],
    },
    {
        id: 6,
        name: 'Axe',
        attributeType: 'Strength',
        theme: 'danger',
        tag: 'Disabler, Initiator',
        shortDescription: "Taunts and forces enemies to attack him.",
        description: "One by one the soldiers of the Red Mist fell, some in battle, others to Mogul Khan's ambitions, until the self-declared general found himself a commander without troops. 'No matter', Axe thought, 'For a one-man army is the best army of all.' — Leaping into battle, Mogul Khan compels nearby foes to attack him with a taunting Berserker's Call. Absorbing blows from every direction, the indomitable Axe reacts by swinging his axe full circle in a Counter Helix, easily dispatching the swarm he had gathered. But alas, not all stay long enough to meet their end. The few limping away from Mogul Khan feel an inexplicable Battle Hunger, a hunger never sated before Axe slams his Culling Blade through a weakened enemy, sending them to an early grave. Axe, Axe is always charging onward.",
        realName: "Mogul Khan, the Axe",
        history1: "As a grunt in the Army of Red Mist, Mogul Khan set his sights on the rank of Red Mist General. In battle after battle he proved his worth through gory deed. His rise through the ranks was helped by the fact that he never hesitated to decapitate a superior. Through the seven year Campaign of the Thousand Tarns, he distinguished himself in glorious carnage, his star of fame shining ever brighter, while the number of comrades in arms steadily dwindled. On the night of ultimate victory, Axe declared himself the new Red Mist General, and took on the ultimate title of 'Axe.' But his troops now numbered zero. Of course, many had died in battle, but a significant number had also fallen to Axe's blade. Needless to say, most soldiers now shun his leadership. But this matters not a whit to Axe, who knows that a one-man army is by far the best.",
        history2: "",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Axe_icon.webp',
        bodyPic: 'assets/images/heroes/axe.jpg',
        attributePic: 'assets/images/heroes/icons/strength.png',
        starred: false,
        winRates: [54.94, 53.94, 53.16, 52.72, 51.98],
        pickRates: [19.30, 18.68, 17.59, 16.63, 13.72],
    },
    {
        id: 7,
        name: 'Bane',
        attributeType: 'Universal',
        theme: 'tertiary',
        tag: 'Support, Disabler',
        shortDescription: "Puts his enemies to sleep, incapacitating them.",
        description: "Formed from the ichor of Nyctasha, Atropos is the vaporous embodiment of pure fear. Sheer terror Enfeebles his enemies, diminishing their efficiency on the battlefield. The Bane Elemental puts heroes to sleep, sending them into a restless and contagious Nightmare as he feeds on their vital energies by Sapping their Brains. Some will never wake. Caught in the Fiend's Grip, Bane's victims can only swing at imagined phantoms as fear chokes the life from their bodies. ",
        realName: "Atropos, the Bane",
        history1: "When the gods have nightmares, it is Bane Elemental who brings them. Also known as Atropos, Bane was born from the midnight terrors of the goddess Nyctasha. A force of terror too powerful to be contained by sleep, he surfaced from her slumbers, fed upon her immortality, and stole his vaporous form from her inky blood. He is the essence of fear. Mortals who hear his voice hear their darkest secrets whispered in their ear. He calls to the hidden fear in every Hero's heart. Wakefulness is no protection, for Bane's black blood, continuously dripping, is a tar that traps his enemies in nightmare. In the presence of Bane, every Hero remembers to fear the dark.",
        history2: "",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Bane_icon.webp',
        bodyPic: 'assets/images/heroes/bane.jpg',
        attributePic: 'assets/images/heroes/icons/universal.png',
        starred: false,
        winRates: [49.55, 51.51, 51.97, 53.25, 53.08],
        pickRates: [4.45, 5.04, 6.10, 7.67, 12.67],
    },
    {
        id: 8,
        name: 'Batrider',
        attributeType: 'Universal',
        theme: 'tertiary',
        tag: 'Disabler, Initiator',
        shortDescription: "Can lasso an enemy away from his team.",
        description: "While most would find being kidnapped by a morde-bat to be a terrifying ordeal, one particular young man found the incident exhilarating. Seeking to relive the thrill of flight, he entered the Yama Raskav Jungle, and came out soaring high above the canopy as the Batrider. Atop his leathery mount, he drenches targets below in Sticky Napalm, increasing their flammability before setting the land ablaze by flying up in the sky glowing like a Firefly. To ignite enemies from afar, he hurls an explosive cocktail with an explosion strong enough to knock foes away. Want a ride? That can be arranged. As he spots his targets from above, and throws out his Flaming Lasso to string them along for a fiery experience they will not soon forget.",
        realName: "Batrider",
        history1: "There is no such thing as harmony among the creatures of the Yama Raskav Jungle. By bite, or claw, or pincer, or hoof, even the slightest sign of weakness means a swift death. They say the Rider was just a lad cutting chaff in his family's field when he was taken, swept up by a massive morde-bat looking for take-out. But this boy had a better idea, and wriggled his way from his captor's grip, onto the beast's back, and hacked it down with his tools. Emerging from the bloody wreckage and intoxicated by the thrill of flight, the boy realized he'd found his calling.",
        history2: "The boy grew, and every summer he'd return to his family's field, often setting out into the bush seeking to reclaim that first thrill of facing death in the form of jaws or a fatal fall. The years went on, but his fire only grew stronger. He studied the overgrowth, plunging deeper with each expedition, until finally he found his way to the caves at the heart of hostility. They say the Rider, on the eve of a scorching summer night, had nothing but a rope, a bottle of liquid courage and a burning determination to feel the skies once more, when he plunged inside…",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Batrider_icon.webp',
        bodyPic: 'assets/images/heroes/batrider.jpg',
        attributePic: 'assets/images/heroes/icons/universal.png',
        starred: false,
        winRates: [41.20, 41.66, 42.98, 44.18, 46.57],
        pickRates: [1.58, 1.63, 1.77, 2.00, 3.49],
    },
    {
        id: 9,
        name: 'Beastmaster',
        attributeType: 'Universal',
        theme: 'tertiary',
        tag: 'Durable, Disabler',
        shortDescription: "Summons beasts to aid his hunt.",
        description: "Raised in the royal menagerie of Slom, Karroch learned to converse with beasts from a young age. With this unique talent, the Beastmaster is able to summon to his side a trusty poison-spitting Boar and a scouting Hawk. In addition to his companions, Karroch has mastered the art of throwing Wild Axes, cutting down trees and foes before returning to his hands. The Beastmaster awakens the Inner Beast of nearby allies, increasing their attack speed. Should an enemy attempt to flee, Karroch lets loose a piercing Primal Roar, incapacitating the target and clearing the path to its demise.",
        realName: "Karroch, the Beastmaster",
        history1: "Karroch was born a child of the stocks. His mother died in childbirth; his father, a farrier for the Last King of Slom, was trampled to death when he was five. Afterward Karroch was indentured to the king's menagerie, where he grew up among all the beasts of the royal court: lions, apes, fell-deer, and things less known, things barely believed in. When the lad was seven, an explorer brought in a beast like none before seen. Dragged before the King in chains, the beast spoke, though its mouth moved not. Its words: a plea for freedom. The King only laughed and ordered the beast perform for his amusement; and when it refused, struck it with the Mad Scepter and ordered it dragged to the stocks.",
        history2: "Over the coming months, the boy Karroch sneaked food and medicinal draughts to the wounded creature, but only managed to slow its deterioration. Wordlessly, the beast spoke to the boy, and over time their bond strengthened until the boy found he could hold up his end of a conversation. He could, in fact, speak now to all the creatures of the King's menagerie. On the night the beast died, a rage came over the boy. He incited the animals of the court to rebel and threw open their cages to set them amok on the palace grounds. The Last King was mauled in the mayhem. In the chaos, one regal stag bowed to the boy who had freed him; and with Beastmaster astride him, leapt the high walls of the estate, and escaped. Now a man, Karroch the Beastmaster has not lost his ability to converse with wild creatures. He has grown into a warrior at one with nature's savagery.",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Beastmaster_icon.webp',
        bodyPic: 'assets/images/heroes/beastmaster.jpg',
        attributePic: 'assets/images/heroes/icons/universal.png',
        starred: false,
        winRates: [45.88, 43.88, 46.07, 46.69, 48.26],
        pickRates: [0.97, 1.06, 1.23, 1.56, 2.59],
    },
    {
        id: 10,
        name: 'Bloodseeker',
        attributeType: 'Agility',
        theme: 'success',
        tag: 'Carry, Nuker',
        shortDescription: "Chases down low health enemies with increased speed.",
        description: "The Flayed Twins' obscene demand for blood could only be met through constant carnage, a task for which Strygwyr was more than suited. Driven by insatiable Thirst, the Bloodseeker senses blood of the mortally wounded from leagues away, and chases them down with eager speed. Through sacred markings on his gear, the blood of the freshly sacrificed flows directly to the Flayed Ones, leaving just enough to mend his wounds and fuel his imbued Rage. Strygwyr paints the land with a crimson ring, silencing foes caught in this Blood Ritual. Forcing difficult decisions on his enemies, for those who run only hasten their own demise. The Bloodseeker Ruptures every artery, causing his victim to hemorrhage with each step. To satisfy the demands of the Flayed Twins, Bloodseeker even goes as far to sacrifice some of his, spraying his own blood around him in a Bloody Mist. By blood loss or by Strygwyr's tribal blades, death is but a foregone conclusion.",
        realName: "Strygwyr, the Bloodseeker",
        history1: "Strygwyr the Bloodseeker is a ritually sanctioned hunter, hound of the Flayed Twins, sent down from the mist-shrouded peaks of Xhacatocatl in search of blood. The Flayed Ones require oceanic amounts of blood to keep them sated and placated, and would soon drain their mountain empire of its populace if the priests of the high plateaus did not appease them. Strygwyr therefore goes out in search of carnage. The vital energy of any blood he lets, flows immediately to the Twins through the sacred markings on his weapons and armor. Over the years, he has come to embody the energy of a vicious hound; in battle he is savage as a jackal. Beneath the Mask of the Bloodseeker, in the rush of bloody quenching, it is said that you can sometime see the features of the Flayers taking direct possession of their hound.",
        history2: "",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Bloodseeker_icon.webp',
        bodyPic: 'assets/images/heroes/bloodseeker.jpg',
        attributePic: 'assets/images/heroes/icons/agility.png',
        starred: false,
        winRates: [49.77, 50.97, 51.13, 50.93, 50.56],
        pickRates: [4.68, 3.92, 3.72, 3.57, 3.09 ],
    },
    {
        id: 11,
        name: 'Bounty Hunter',
        attributeType: 'Agility',
        theme: 'success',
        tag: 'Escape, Nuker',
        shortDescription: "Loots and collects bounties off of his enemies.",
        description: "Fear is the mother of rumor, and tales of Gondar's origins are nothing but hearsay. For the right price, the Bounty Hunter will Track down any target to deliver their heads and collect their bounties. He Guides while Walking through Shadows into the best-guarded keeps, crippling his target with a surprise attack, and steal some of their riches with a Calculated Strike. Even targets at a greater distance are not safe from the Bounty Hunter, as his trusty Shuriken seemingly has a mind on its own, seeking out and striking all targets the Bounty Hunter keeps track of. Because in the end, it's all about the gold. ",
        realName: "Gondar, the Bounty Hunter",
        history1: "When the hunted tell tales of Gondar the Bounty Hunter, none are sure of which are true. In whispered tones they say he was abandoned as a kit, learning his skill in tracking as a matter of simple survival. Others hear he was an orphan of war, taken in by the great Soruq the Hunter to learn the master's skill with a blade as they plumbed the dark forests for big game. Still others believe he was a lowly street urchin raised among a guild of cutpurses and thieves, trained in the arts of stealth and misdirection. Around campfires in the wild countryside his quarry speaks the rumors of Gondar's work, growing ever more fearful: they say it was he who tracked down the tyrant King Goff years after the mad regent went into hiding, delivering his head and scepter as proof. That it was he who infiltrated the rebel camps at Highseat, finally bringing the legendary thief White Cape to be judged for his crimes. And that it was he who ended the career of Soruq the Hunter, condemned as a criminal for killing the Prince's prized hellkite. The tales of Gondar's incredible skill stretch on, with each daring feat more unbelievable than the last, each target more elusive. For the right price, the hunted know, anyone can be found. For the right price, even the mightiest may find fear in the shadows.",
        history2: "",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Bounty_Hunter_icon.webp',
        bodyPic: 'assets/images/heroes/bounty_hunter.jpg',
        attributePic: 'assets/images/heroes/icons/agility.png',
        starred: false,
        winRates: [49.23, 49.25, 49.57, 50.12, 51.14],
        pickRates: [9.99, 8.15, 7.27, 6.92, 7.47],
    },
    {
        id: 12,
        name: 'Brewmaster',
        attributeType: 'Universal',
        theme: 'tertiary',
        tag: 'Initiator, Durable, Disabler',
        shortDescription: "Splits into elemental spirits with unique abilities.",
        description: "For nine days Mangix fought the master of his order, both warriors swilling and striking in equal measure, until at last the elder collapsed into a drunken stupor. Having claimed the title of Brewmaster, Mangix now wanders the land as a Drunken Brawler, swinging and evading with unpredictable finesse. Under one arm he holds a great keg, and not merely for storing his Cinder Brew. Mangix drenches himself and enemies in alcohol, strengthening himself in an advanced state of inebriation based on his stance, while disorienting enemies before slamming the barrel down with a Thunder Clap. Rumor around taverns is that the Brewmaster is actually composed of Elemental Spirits, each with their own unique abilities, and should one catch him sufficiently intoxicated, one may just witness this Primal Split in action.",
        realName: "Mangix, the Brewmaster",
        history1: "Deep in the Wailing Mountains, in a valley beneath the Ruined City, the ancient Order of the Oyo has for centuries practiced its rites of holy reverie, communing with the spirit realm in grand festivals of drink. Born to a mother's flesh by a Celestial father, the youth known as Mangix was the first to grow up with the talents of both lineages. He trained with the greatest aesthetes of the Order, eventually earning, through diligent drunkenness, the right to challenge for the title of Brewmaster, that appellation most honored among the contemplative malt-brewing sect.",
        history2: "As much drinking competition as mortal combat, Mangix for nine days drank and fought the elder master. For nine nights they stumbled and whirled, chugged and struck, until at last the elder warrior collapsed into a drunken stupor, and a new Brewmaster was named. Now the new, young Brewmaster calls upon the strength of his Oyo forebears to speed his staff. When using magic, it is to his spirit ancestors that he turns. Like all Brewmasters before him, he was sent out from his people with a single mission. He wanders the land, striving toward enlightenment through drink, searching for the answer to the ancient spiritual schism. Hoping to think the single thought that will unite the spirit and physical planes again.",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Brewmaster_icon.webp',
        bodyPic: 'assets/images/heroes/brewmaster.jpg',
        attributePic: 'assets/images/heroes/icons/universal.png',
        starred: false,
        winRates: [49.21, 49.73, 50.87, 51.51, 52.26],
        pickRates: [1.43, 1.67, 2.22, 3.18, 5.23],
    },
    {
        id: 13,
        name: 'Bristleback',
        attributeType: 'Strength',
        theme: 'danger',
        tag: 'Carry, Durable, Nuker',
        shortDescription: "Takes reduced damage when facing away from enemies.",
        description: "The enforcer at a local pub, Rigwarl's never failed to collect a tab. That is, until he met one tough customer from the north. For the first time in his life, Rigwarl felt the need to train. His Thorny Back deters attacks while peppering foes with constant barrages of Quill Sprays. From his nose he blows Thick Gobs of Snot, slowing and covering opponents in goo. When it comes to a fight, he really puts his back into it. With every volley and every Sneeze, Rigwarl works himself into a fury, adding rage to each blow as he goes on the Warpath in search of a rematch. ",
        realName: "Rigwarl, the Bristleback",
        history1: "Never one to turn his back on a fight, Rigwarl was known for battling the biggest, meanest scrappers he could get his hands on. Christened Bristleback by the drunken crowds, he waded into backroom brawls in every road tavern between Slom and Elze, until his exploits finally caught the eye of a barkeep in need of an enforcer. For a bit of brew, Bristleback was hired to collect tabs, keep the peace, and break the occasional leg or two (or five, in the case of one unfortunate web-hund).",
        history2: "After indulging in a night of merriment during which bodily harm was meted out in equal parts upon both delinquent patrons and his own liver, Bristleback finally met his match. \"Your tusks offend me, sir,\" he was heard to drunkenly slur to one particularly large fellow from the northern wastes whose bill had come due. What followed was a fight for the ages. A dozen fighters jumped in. No stool was left unbroken, and in the end, the impossible happened: the tab went unpaid. Over the weeks that followed, Bristleback's wounds healed, and his quills grew back; but an enforcer's honor can be a prickly thing. He paid the tab from his own coin, vowing to track down this northerner and extract redemption. And then he did something he'd never done before: he actually trained, and in so doing made a startling discovery about himself. A smile peeled back from his teeth as he flexed his quills. Turning his back to a fight might be just the thing.",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Bristleback_icon.webp',
        bodyPic: 'assets/images/heroes/bristleback.jpg',
        attributePic: 'assets/images/heroes/icons/strength.png',
        starred: false,
        winRates: [52.73, 50.17, 49.37, 49.56, 49.42],
        pickRates: [13.98, 11.67, 10.63, 10.05, 10.33],
    },
    {
        id: 14,
        name: 'Broodmother',
        attributeType: 'Universal',
        theme: 'tertiary',
        tag: 'Carry, Pusher, Escape',
        shortDescription: "Hunts with her army of Spiderlings.",
        description: "Inhabiting the lava tubes below the caldera of Mount Pyrotheos, Black Arachnia grew tired of recent adventurers stepping on her many offspring. And so, the Broodmother set out to rid the world of every potential intruder, one hero at a time. Warm bodies make ideal nurseries, a fact not lost on Black Arachnia as she injects her eggs into dying foes to Spawn Spiderlings. Across patches of land she Spin Webs of Silken Fiber, sheltering herself within to recuperate injuries or laying down Snares to catch her prey. Driven by an Insatiable Hunger, the Broodmother goes into a feeding frenzy, sucking the vital fluids from wandering heroes with each bite, replenishing herself for the next spawn cycle. ",
        realName: "Black Arachnia, the Broodmother",
        history1: "For centuries, Black Arachnia the Broodmother lurked in the dark lava tubes beneath the smoldering caldera of Mount Pyrotheos, raising millions of spiderlings in safety before sending them to find prey in the wide world above. In a later age, the Vizier of Greed, Ptholopthales, erected his lodestone ziggurat on the slopes of the dead volcano, knowing that any looters who sought his magnetic wealth must survive the spider-haunted passages.",
        history2: "After millennia of maternal peace, Black Arachnia found herself beset by a steady trickle of furfeet and cutpurses, bold knights and noble youths--all of them delicious, certainly, and yet tending to create a less than nurturing environment for her innocent offspring. Tiring of the intrusions, she paid a visit to Ptholopthales; and when he proved unwilling to discuss a compromise, she wrapped the Vizier in silk and set him aside to be the centerpiece of a special birthday feast.",
        history3: "Unfortunately, the absence of the Magnetic Ziggurat's master merely emboldened a new generation of intruders. When one of her newborns was trodden underfoot by a clumsy adventurer, she reached the end of her silken rope. Broodmother headed for the surface, declaring her intent to rid the world of each and every possible invader, down to the last Hero if necessary, until she could ensure her nursery might once more be a safe and wholesome environment for her precious spiderspawn.",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Broodmother_icon.webp',
        bodyPic: 'assets/images/heroes/broodmother.jpg',
        attributePic: 'assets/images/heroes/icons/universal.png',
        starred: false,
        winRates: [44.61, 47.40, 49.48, 51.47, 53.33],
        pickRates: [2.90, 2.33, 2.23, 2.52, 3.98],
    },
    {
        id: 15,
        name: 'Centaur Warrunner',
        attributeType: 'Strength',
        theme: 'danger',
        tag: 'Durable, Initiator, Disabler',
        shortDescription: "Reflects damage back to his attackers. ",
        description: "Some write to express their being, others paint or sing. But for the centaurs of Druud, there is no higher art than the art of killing. And in that, none was more accomplished than Bradwarden. With skills acquired in the arena, the Warrunner punishes his opponents and instantly Retaliates their every attack, disregarding harm to himself as he metes out a fearsome Double Edge. Ever in search of a worthy opponent, the Work Horse rouses his allies, and sometimes Hitching them on his back for a ride, to charge down enemies in a wild Stampede, quickening the pace of the carnage. Once battle is joined, the Centaur Warrunner Stomps and tramples surrounding foes, stunning them just long enough for his battleaxe to sink in.",
        realName: "Bradwarden, the Centaur Warrunner",
        history1: "It's said that a centaur's road is paved with the corpses of the fallen. For the one called Warrunner, it has been a long road indeed. To outsiders, the four-legged clans of Druud are often mistaken for simple, brutish creatures. Their language has no written form; their culture lacks pictographic traditions, structured music, formalized religion. For centaurs, combat is the perfect articulation of thought, the highest expression of self. If killing is an art among centaurs, then Bradwarden the Warrunner is their greatest artist. He rose to dominance on the proving grounds of Omexe, an ancient arena where centaur clans have for millennia gathered to perform their gladiatorial rites. As his fame spread, spectators came from far and wide to see the great centaur in action. Always the first to step into the arena, and the last to leave, he composes a masterpiece in each guttering spray, each thrust of blood-slickened blade-length. It is the poetry of blood on steel, flung in complex patterns across the pale sands of the killing floor.",
        history2: "Warrunner defeated warrior after warrior, until the arena boomed with the cheering of his name, and he found himself alone, the uncontested champion of his kind. The great belt of Omexe was bestowed, wrapped around his broad torso, but in his victory, the death-artist found only emptiness. For what is a warrior without a challenge? The great centaur galloped out of Omexe that day with a new goal. To his people, Warrunner is the greatest warrior to ever step into the arena. Now he has set out to prove he is the greatest fighter who has ever lived.",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Centaur_Warrunner_icon.webp',
        bodyPic: 'assets/images/heroes/centaur.jpg',
        attributePic: 'assets/images/heroes/icons/strength.png',
        starred: false,
        winRates: [51.95, 51.72, 52.08, 51.94, 51.58],
        pickRates: [6.08, 7.65, 8.62, 9.40, 10.75],
    },
    {
        id: 16,
        name: 'Chaos Knight',
        attributeType: 'Strength',
        theme: 'danger',
        tag: 'Disabler, Nuker, Carry',
        shortDescription: "Has strong but random damage output.",
        description: "Upon the black steed Armageddon, the Chaos Knight rode into countless battles with a single purpose in mind: To extinguish that which he knows as \"The Light\". Like a roll of unseen dice, the oldest Fundamental stuns his targets with a Chaotic Bolt, and then Strikes with life-stealing attacks that deal highly irregular amounts of damage. Those who escape the initial onslaught find themselves in a Reality Rift, reappearing inexplicably at Armageddon's side, exposed for its rider's wrath. Flanked by several images of himself, the Chaos Knight and his apocalyptic Phantasms hack their opponents apart with the strength of multiple heroes. ",
        realName: "Chaos Knight",
        history1: "The veteran of countless battles on a thousand worlds, Chaos Knight hails from a far upstream plane where the fundamental laws of the universe have found sentient expression. Of all the ancient Fundamentals, he is the oldest and most tireless, endlessly searching out a being he knows only as \"The Light.\" Long ago the Light ventured out from the progenitor realm, in defiance of the first covenant. Now Chaos Knight shifts from plane to plane, always on the hunt to extinguish the Light wherever he finds it. A thousand times he has snuffed out the source, and always he slides into another plane to continue his search anew.",
        history2: "Upon his steed Armageddon he rides, wading into battle with maniacal frenzy, drawing strength from the disorder of the universe. A physical manifestation of chaos itself, in times of need he calls upon other versions of himself from other planes, and together these dark horsemen ride into battle, as unstoppable as any force of nature. Only when the last Light of the world is scoured from existence will the search be ended. Where rides the Chaos Knight, death soon follows.",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Chaos_Knight_icon.webp',
        bodyPic: 'assets/images/heroes/chaos_knight.jpg',
        attributePic: 'assets/images/heroes/icons/strength.png',
        starred: false,
        winRates: [47.84, 47.93, 47.40, 47.15, 48.22],
        pickRates: [6.35, 5.02, 4.28, 3.87, 3.85],
    },
    {
        id: 17,
        name: 'Chen',
        attributeType: 'Universal',
        theme: 'tertiary',
        tag: 'Support, Pusher',
        shortDescription: "Converts creeps to his cause, building an army.",
        description: "Converted at sword-point after a disastrous battle, Chen quickly became one of the Fold's most zealous knights. Raised among the clans of the Hazhadal Barrens, Chen adapts his skills of animal enthrallment to perform Holy Persuasions and Martyrdoms, compelling packs of creatures of the forest to fight and sacrifice for his cause. His allies are graced with Divine Favor, while foes are forced to atone through the magnified pains of Penitence. Chen's devotion does not go unrewarded. The Hand of God aids his companions in their quests, intervening at critical moments to heal their injuries and save them from fatal blows.",
        realName: "Chen, the Holy Knight",
        history1: "Born in the godless Hazhadal Barrens, Chen came of age among the outlaw tribes who eked out an existence in the shimmering heat of the desert. Using an ancient form of animal enthrallment, Chen's people husbanded the hardy desert locuthi, a stunted species of burrowing dragon that melted desert sands into tubes of glass where twice-a-year rains collected. Always on the edge of starvation and thirst, fighting amongst their neighbors and each other, Chen's clan made the mistake, one fateful day, of ambushing the wrong caravan.",
        history2: "In the vicious battle that followed, Chen's clan was outmatched. The armored Knights of the Fold made short work of the enthralled locuthi, who attacked and died in waves. With their dragons dead, the tribesmen followed. Chen struggled, and slashed, and clawed, and perished—or would have. Defeated, on his knees, he faced his execution with humility, offering his neck to the blade. Moved by Chen's obvious courage, the executioner halted his sword. Instead of the blade, Chen was given a choice: death or conversion. Chen took to the faith with a ferocity. He joined the Fold and earned his armor one bloody conversion at a time. Now, with the fanaticism of a convert, and with his powers of animal enthrallment at their peak, he seeks out unbelievers and introduces them to their final reward.",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Chen_icon.webp',
        bodyPic: 'assets/images/heroes/chen.jpg',
        attributePic: 'assets/images/heroes/icons/universal.png',
        starred: false,
        winRates: [42.72, 45.16, 46.90, 49.31, 51.56],
        pickRates: [0.82, 0.80, 0.91, 1.12, 1.96],
    },
    {
        id: 18,
        name: 'Clinkz',
        attributeType: 'Agility',
        theme: 'success',
        tag: 'Carry, Escape, Pusher',
        shortDescription: "Stalks invisibly to ambush lone enemies.",
        description: "As Clinkz loosed his final arrow, the demon Maraxiform ignited the land with Hellfire, burning him to the bone. Yet, the heroic bowman did not die. He had slain the demon, and unwittingly earned king-mage Sutherex's reward — Eternal life. Immortalized at the precipice of death, Clinkz now makes advantageous use of his skeletal body. Camouflaged, he walks into hostile lands, forming Death Pacts with wildlife to learn their ways and empower his shots and vitality. The demon's inferno burns within his ribs, with which he now rains Fiery Death upon his foes, Searing His Arrows to devastating effect. When backup is needed, Clinkz calls upon a Burning Army of skeletal compatriots, incinerating his foe in flames of their Hellfire barrage.",
        realName: "Clinkz, the Bone Fletcher",
        history1: "At the base of the Bleeding Hills stretches a thousand-league wood, a place called the Hoven, where black pools gather the tarry blood of the uplands, and the king-mage Sutherex sits in benevolent rule. Once a sworn protector of the Hoven lands, Clinkz earned a reputation for his skill with a bow. In the three-hundredth year of the king-mage, the demon Maraxiform rose from Sixth Hell to lay claim to the forest. In response, the king-mage decreed an unbreakable spell: to any who slew the demon would be granted Life Without End.",
        history2: "Unaware of the spell, Clinkz waded into battle, defending his lands against the demon's fiery onslaught. Clinkz drove Maraxiform back to the gates of Sixth Hell itself, where on that fiery threshold the two locked in a mortal conflict. Grievously wounded, the demon let out a blast of Hellfire as Clinkz loosed his final arrow. The arrow struck the demon true as Hellfire poured out across the land, lighting the black pools and burning Clinkz alive at the instant of the demon's death. Thus, the mage's spell took effect at the very moment of the archer's conflagration, preserving him in this unholy state, leaving him a being of bones and rage, caught in the very act of dying, carrying Hell's breath with him on his journey into eternity.",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Clinkz_icon.webp',
        bodyPic: 'assets/images/heroes/clinkz.jpg',
        attributePic: 'assets/images/heroes/icons/agility.png',
        starred: false,
        winRates: [51.67, 51.55, 51.46, 51.21, 50.82],
        pickRates: [9.09, 7.35, 7.34, 7.60, 8.53],
    },
    {
        id: 19,
        name: 'Clockwerk',
        attributeType: 'Universal',
        theme: 'tertiary',
        tag: 'Initiator, Disabler, Durable',
        shortDescription: "Launches himself into enemies with his hookshot.",
        description: "Powered by revenge and ingenuity, Rattletrap armored himself into an instrument of war. Firing Rockets from his shoulder-mounted launcher, striking and revealing distant territories. With a built-in Jetpack for scouting convenience, a sudden Hookshot flies, latching instantly and pulling the mechanized Keen to his unsuspecting foe. Before the stunned target could react, Rattletrap erects a grid of Power Cogs, isolating and trapping his foe within while repelling help from without. He triggers the suit's Battery Assault, and watches the target panic as short bursts of shrapnel whittle down its remaining health... and if all that was not enough, Overclocking the armored suit and repeating the assault at higher speeds may do the trick.",
        realName: "Rattletrap, the Clockwerk",
        history1: "Rattletrap descends from the same far-flung kindred as Sniper and Tinker, and like many of the Keen Folk, has offset his diminutive stature through the application of gadgetry and wit. The son of the son of a clockmaker, Rattletrap was many years apprenticed to that trade before war rode down from the mountains and swept the plains villages free of such innocent vocations. \"Your new trade is battle,\" his dying father told him as the village of their ancestors lay in charred and smoking ruins.",
        history2: "It is a poor tradesman who blames his tools, and Rattletrap was never one to make excuses. After burying his father among the ruins of their village, he set about to transform himself into the greatest tool of warfare that any world had ever seen. He vowed to never again be caught unprepared, instead using his talents to assemble a suit of powered Clockwerk armor to make the knights of other lands look like tin cans by comparison. Now Rattletrap is alive with devices, a small but deadly warrior whose skills at ambush and destruction have risen to near-automated levels of efficiency. An artisan of death, his mechanizations make short work of the unwary, heralding a new dawn in this age of warfare. What time is it? It's Clockwerk time!",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Clockwerk_icon.webp',
        bodyPic: 'assets/images/heroes/rattletrap.jpg',
        attributePic: 'assets/images/heroes/icons/universal.png',
        starred: false,
        winRates: [48.99, 49.40, 48.99, 49.77, 49.62],
        pickRates: [4.13, 5.02, 5.27, 5.44, 5.76],
    },
    {
        id: 20,
        name: 'Crystal Maiden',
        attributeType: 'Intelligent',
        theme: 'primary',
        tag: 'Support, Disabler, Nuker',
        shortDescription: "Unleashes a high damage blizzard upon her foes.",
        description: "Wherever Rylai went, the cold went with her. Fields and orchards withered in her wake, leaving her parents no choice but to pack her off to Icewrack, a realm in the frigid north. Under the tutelage of a hermit wizard, Rylai learned to imprison her enemies with a Thick Block of Ice, holding them in place as she Freezes the Ground. Magic flourishes under her, stimulating Arcane Energy Regeneration in all her companions. In the heat of battle, Rylai keeps a cool head. Channeling her Elemental Talents, the Crystal Maiden summons enormous shards of ice from the skies, obliterating all foes foolish enough to remain in her Freezing Field.",
        realName: "Rylai, the Crystal Maiden",
        history1: "Born in a temperate realm, raised with her fiery older sister Lina, Rylai the Crystal Maiden soon found that her innate elemental affinity to ice created trouble for all those around her. Wellsprings and mountain rivers froze in moments if she stopped to rest nearby; ripening crops were bitten by frost, and fruiting orchards turned to mazes of ice and came crashing down, spoiled. When their exasperated parents packed Lina off to the equator, Rylai found herself banished to the cold northern realm of Icewrack, where she was taken in by an Ice Wizard who had carved himself a hermitage at the crown of the Blueheart Glacier. After long study, the wizard pronounced her ready for solitary practice and left her to take his place, descending into the glacier to hibernate for a thousand years. Her mastery of the Frozen Arts has only deepened since that time, and now her skills are unmatched.",
        history2: "",
        history3: "",
        history4: "",
        profilePic: 'assets/images/heroes/icons/Crystal_Maiden_icon.webp',
        bodyPic: 'assets/images/heroes/crystal_maiden.jpg',
        attributePic: 'assets/images/heroes/icons/intelligent.png',
        starred: false,
        winRates: [51.09, 49.65, 49.15, 48.21, 48.06],
        pickRates: [15.04, 12.71, 11.65, 11.01, 10.76],
    },
]