import { Item } from './templates';

export const ITEMS: Item[] = [
    {   
        name: 'Tranquil Boots',
        cost: '925',
        bonus: '+65 Movement Speed,+14 Health Regeneration',
        active: '',
        passive: 'Passive: Break',
        icon: 'assets/images/items/Tranquil_Boots_(Active)_icon.webp',
        description: 'While they increase the longevity of the wearer, this boot is not particularly reliable.',
    },
    {   
        name: 'Arcane Boots',
        cost: '1300',
        bonus: '+45 Movement Speed,+0.75 Mana Regeneration',
        active: 'Active: Replenish Mana',
        passive: 'Passive: Basilius Aura',
        icon: 'assets/images/items/Arcane_Boots_icon.webp',
        description: 'Magi equipped with these boots are valued in battle.',
    },
    {   
        name: 'Power Treads',
        cost: '1400',
        bonus: '+45 Movement Speed,+10 Selected Attribute,+25 Attack Speed',
        active: 'Active: Switch Attribute',
        passive: '',
        icon: 'assets/images/items/Power_Treads_icon.webp',
        description: 'A pair of tough-skinned boots that change to meet the demands of the wearer.',
    },
    {   
        name: 'Phase Boots',
        cost: '1500',
        bonus: '+50 Movement Speed,+12 Damage, +4 Armor',
        active: 'Active: Phase',
        passive: '',
        icon: 'assets/images/items/Phase_Boots_icon.webp',
        description: 'Boots that allow the weaver to travel between the ether.',
    },
    {   
        name: 'Blink Dagger',
        cost: '2250',
        bonus: '',
        active: 'Active: Blink',
        passive: '',
        icon: 'assets/images/items/Blink_Dagger_icon.webp',
        description: 'The fabled dagger used by the fastest assassin ever to walk the lands.',
    },
    {   
        name: 'Vanguard',
        cost: '1700',
        bonus: '+250 Health,+4.5 Health Regeneration',
        active: '',
        passive: 'Passive: Damage Block',
        icon: 'assets/images/items/Vanguard_icon.webp',
        description: 'A powerful shield that defends its wielder from even the most vicious attacks.',
    },
    {   
        name: 'Refresher Orb',
        cost: '5000',
        bonus: '+18 Health Regeneration,+8 Mana Regeneration,+10 Damage',
        active: 'Active: Reset Cooldowns',
        passive: '',
        icon: 'assets/images/items/Refresher_Orb_icon.webp',
        description: 'A powerful artifact created for wizards.',
    },
    {   
        name: 'Aghanim\'s Scepter',
        cost: '4200',
        bonus: '+10 All Attributes,+175 Health,+175 Mana',
        active: '',
        passive: 'Passive: Ability Upgrade',
        icon: 'assets/images/items/Aghanims_Scepter_icon.webp',
        description: 'The scepter of a wizard with demigod-like powers.',
    },
    {   
        name: 'Harpoon',
        cost: '4700',
        bonus: '+25 Strength,+10 Agility,+10 Intelligent,+2 Mana Regeneration,+25 Attack Damage',
        active: 'Active: Draw Forth',
        passive: 'Passive: Echo Strike',
        icon: 'assets/images/items/Harpoon_icon.webp',
        description: '',
    },
    {   
        name: 'Abyssal Blade',
        cost: '6250',
        bonus: '+10 Strength,+250 Health,+10 Health Regeneration,+35 Attack Damage',
        active: 'Active: Overwhelm',
        passive: 'Passive: Bash, Damage Block',
        icon: 'assets/images/items/Abyssal_Blade_icon.webp',
        description: 'The lost blade of the Commander of the Abyss, this edge cuts into an enemy\'s soul.',
    },
    {   
        name: 'Battle Fury',
        cost: '4100',
        bonus: '+7.5 Health Regeneration,+2.75 Mana Regeneration,+65 Attack Damage',
        active: 'Active: Chop Tree',
        passive: 'Passive: Quell, Cleave',
        icon: 'assets/images/items/Battle_Fury_icon.webp',
        description: 'The bearer of this mighty axe gains the ability to cut down swaths of enemies at once.',
    },
    {   
        name: 'Linken\'s Sphere',
        cost: '4800',
        bonus: '+16 Strength,+16 Agility,+16 Intelligent,+6 Health Regeneration,+4.25 Mana Regeneration',
        active: 'Active: Transfer Spellblock',
        passive: 'Passive: Spellblock',
        icon: 'assets/images/items/Linkens_Sphere_icon.webp',
        description: 'This magical sphere once protected one of the most famous heroes in history.',
    },
    {   
        name: 'Aeon Disk',
        cost: '3000',
        bonus: '+250 Health,+300 Mana',
        active: '',
        passive: 'Passive: Combo Breaker',
        icon: 'assets/images/items/Aeon_Disk_icon.webp',
        description: 'A powerful artifact long ago smuggled out of the Ivory Incubarium. Or so many believe.',
    },
    {   
        name: 'Silver Edge',
        cost: '5450',
        bonus: '+60 Attack Damage,+35 Attack Speed',
        active: 'Active Shadow Walk',
        passive: '',
        icon: 'assets/images/items/Silver_Edge_icon.webp',
        description: 'Once used to slay an unjust king, only to have the kingdom erupt into civil war in the aftermath.',
    },
    {   
        name: 'Daedalus',
        cost: '5100',
        bonus: '+88 Attack Damage',
        active: '',
        passive: 'Passive: Critical Strike',
        icon: 'assets/images/items/Daedalus_icon.webp',
        description: 'A weapon of incredible power that is difficult for even the strongest of warriors to control. ',
    },

]